### ISSUE TITLE
Possible incomplete code snippet for anonymous functions (kindle/android)

### ISSUE THREAD

**Issue by focusaurus** [bobstrecansky/HighPerformanceWithGo#4]
Reading on an android tablet in the kindle app, the third code snippet in ch  3 section "Anonymous functions" looks like maybe a line got skipped. Will attach screenshot.
![Screenshot_20210602-143840](https://user-images.githubusercontent.com/482377/120549422-d202ee80-c3b0-11eb-8b37-8369b04ca251.jpg)

**Comment by bobstrecansky** [comment]
Was unable to get this formatting changed.
